# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
