# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0004_bar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='visitas',
            field=models.IntegerField(blank=True, default=0, max_length=2147483646),
            preserve_default=False,
        ),
    ]
