# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0005_bar_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='visitas',
            field=models.IntegerField(),
        ),
    ]
