# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0008_bar_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='lema',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='bar',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
