# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0009_auto_20151217_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='logo',
            field=models.ImageField(default=0, upload_to=b'photos'),
            preserve_default=False,
        ),
    ]
