# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0010_bar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='logo',
            field=models.ImageField(upload_to=b'logos'),
        ),
    ]
