# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0011_auto_20151221_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='logo',
            field=models.ImageField(upload_to=b'/'),
        ),
    ]
