# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0012_auto_20151221_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='logo',
            field=models.ImageField(default=b'/static/Bares/logos/building.jpg', upload_to=b'/static/Bares/logos/'),
        ),
    ]
