# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0019_tapa_megustas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='cerveza',
            field=models.IntegerField(default=1),
        ),
    ]
