# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0020_bar_cerveza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='cerveza',
        ),
        migrations.AddField(
            model_name='bar',
            name='precio_cerveza',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
