# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0023_auto_20160105_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='precio_cervez',
        ),
        migrations.AddField(
            model_name='bar',
            name='precio_cerveza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
